server:
  port: ${PORT:8082}

spring:
  application:
    name: ms-inventario

  datasource:
    url: ${JDBC_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      data-source-properties:
        oracle.net.authentication_services: "()"

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect

# Configuración de OpenAPI / Swagger
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html

# Niveles de Logs para Debug
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
    com:
      zaxxer:
        hikari: DEBUG

# Comunicación con otros Microservicios
ms:
  producto:
    # En tu PC usará localhost:8080 por defecto, en Render inyectarás la URL real
    url: ${MS_PRODUCTO_URL:lb://ms-producto}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://ms-eureka-con:8761/eureka/}
  instance:
    prefer-ip-address: true
