spring:
  application:
    name: ms-producto  # <-- CORREGIDO: Esto es lo que verá Eureka
  datasource:
    url: ${JDBC_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 5
      data-source-properties:
        oracle.net.authentication_services: "()"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect

server:
  port: ${PORT:8089}

ms:
  categoria:
    url: ${MS_CATEGORIA_URL:lb://ms-categoria}

logging:
  level:
    org.hibernate.SQL: DEBUG
    com.zaxxer.hikari: DEBUG

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://ms-eureka-con:8761/eureka/}
  instance:
    prefer-ip-address: true  # <-- CRÍTICO: Para que el Gateway encuentre la IP en Docker

---
spring:
  config:
    activate:
      on-profile: remote
ms:
  categoria:
    url: lb://ms-categoria