spring:
  application:
    name: ms-producto

  datasource:
    url: jdbc:oracle:thin:@hospitalv11_high?TNS_ADMIN=C:/Users/Fuyu/Desktop/Duoc/Semestre3/FullStack1
    username: producto_bodega
    password: FullStack-001
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect

  # 🔥 IMPORTANTE: evita error si no activas perfil
  profiles:
    active: dev

server:
  port: ${PORT:8089}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.zaxxer.hikari: DEBUG

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

# =========================
# PERFIL DEV (LOCAL)
# =========================
---
spring:
  config:
    activate:
      on-profile: dev

ms:
  categoria:
    url: http://localhost:8083

# =========================
# PERFIL REMOTE (EUREKA)
# =========================
---
spring:
  config:
    activate:
      on-profile: remote

ms:
  categoria:
    url: lb://ms-categoria