spring:
  application:
    name: ms-producto

  datasource:
    url: ${JDBC_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect

  profiles:
    active: dev

server:
  port: ${PORT:8089}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.zaxxer.hikari: DEBUG

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

# =========================
# PERFIL DEV (LOCAL)
# =========================
---
spring:
  config:
    activate:
      on-profile: dev

ms:
  categoria:
    url: ${MS_CATEGORIA_URL}

# =========================
# PERFIL REMOTE (EUREKA)
# =========================
---
spring:
  config:
    activate:
      on-profile: remote

ms:
  categoria:
    url: lb://ms-categoria