server:
  port: ${PORT:8080}

spring:
  application:
    name: ms-gateway
  
  cloud:
    gateway:
      routes:
        # 1. Alerta
        - id: ms-alerta-route
          uri: ${MS_ALERTA_URI:lb://ms-alerta}
          predicates:
            - Path=/alertas/**

        # 2. Auditoría
        - id: ms-auditoria-route
          uri: ${MS_AUDITORIA_URI:lb://ms-auditoria}
          predicates:
            - Path=/auditorias/**

        # 3. Categoría
        - id: ms-categoria-route
          uri: ${MS_CATEGORIA_URI:lb://ms-categoria}
          predicates:
            - Path=/categorias/**

        # 4. Inventario
        - id: ms-inventario-route
          uri: ${MS_INVENTARIO_URI:lb://ms-inventario}
          predicates:
            - Path=/inventarios/**

        # 5. Lote
        - id: ms-lote-route
          uri: ${MS_LOTE_URI:lb://ms-lote}
          predicates:
            - Path=/lotes/**

        # 6. Movimiento
        - id: ms-movimiento-route
          uri: ${MS_MOVIMIENTO_URI:lb://ms-movimiento}
          predicates:
            - Path=/movimientos/**

        # 7. Producto
        - id: ms-producto-route
          uri: ${MS_PRODUCTO_URI:lb://ms-producto}
          predicates:
            - Path=/productos/**

        # 8. Proveedor
        - id: ms-proveedor-route
          uri: ${MS_PROVEEDOR_URI:lb://ms-proveedor}
          predicates:
            - Path=/proveedores/**

        # 9. Reporte
        - id: ms-reporte-route
          uri: ${MS_REPORTE_URI:lb://ms-reporte}
          predicates:
            - Path=/reportes/**

        # 10. Usuario
        - id: ms-usuario-route
          uri: ${MS_USUARIO_URI:lb://ms-usuario}
          predicates:
            - Path=/usuarios/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}