# CONFIGURACIÓN BASE (Común para todos los entornos)
spring:
  application:
    name: ms-usuario
  datasource:
    url: ${JDBC_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 5
      # Propiedades críticas para que el driver use seguridad pura de Java (evita el freeze en Docker)
      data-source-properties:
        oracle.net.authentication_services: "()"
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect

server:
  # IE 3.3.1: Puerto dinámico. Usa el 8081 por defecto o el asignado por la nube (PaaS) [5, 6]
  port: ${PORT:8081}

# Registro en Eureka (Obligatorio para Evaluación 3) [4, 7]
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

# Configuración de Logs para Trazabilidad y Debugging (IE 2.3.2) [6]
logging:
  level:
    org.hibernate.SQL: DEBUG
    com.example.ms_usuario: DEBUG
    com.zaxxer.hikari: DEBUG

---
# PERFIL DE DESARROLLO (Local) [2, 4]
spring:
  config:
    activate:
      on-profile: dev

---
# PERFIL REMOTO (Docker / Railway / Render) [2, 4, 8]
spring:
  config:
    activate:
      on-profile: remote