spring.application.name=ms-inventario
server.port=8082

ms.producto.url=http://localhost:8080

spring.datasource.url=jdbc:oracle:thin:@jq2igswt1161sofw_high?TNS_ADMIN=C:/Users/Fuyu/Desktop/Duoc/Semestre3/FullStack1/Wallet_JQ2IGSWT1161SOFW
spring.datasource.username=ADMIN
spring.datasource.password=FullStack-001
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

logging.level.org.hibernate.SQL=DEBUG
logging.level.com.zaxxer.hikari=DEBUG