spring:
  application:
    name: ms-movimiento

  datasource:
    url: ${JDBC_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 10
      data-source-properties:
        oracle.net.authentication_services: "()"

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true

server:
  port: ${PORT:8084}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://ms-eureka-con:8761/eureka/}
  instance:
    prefer-ip-address: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    com.zaxxer.hikari: DEBUG

ms:
  producto:
    url: ${MS_PRODUCTO_URL:lb://ms-producto}
  inventario:
    url: ${MS_INVENTARIO_URL:lb://ms-inventario}

---
spring:
  config:
    activate:
      on-profile: remote

ms:
  producto:
    url: lb://ms-producto
  inventario:
    url: lb://ms-inventario
